In [13]:
import yfinance as yf
import pandas as pd

# Download NIFTY 50 data
ticker = "^NSEI"

data = yf.download(ticker, start="2015-01-01", end="2025-01-01")

# Show first rows
data.head()

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open  Volume
Ticker            ^NSEI        ^NSEI        ^NSEI        ^NSEI   ^NSEI
Date
2015-01-02  8395.450195  8410.599609  8288.700195  8288.700195  101900
2015-01-05  8378.400391  8445.599609  8363.900391  8407.950195  118200
2015-01-06  8127.350098  8327.849609  8111.350098  8325.299805  172800
2015-01-07  8102.100098  8151.200195  8065.450195  8118.649902  164100
2015-01-08  8234.599609  8243.500000  8167.299805  8191.399902  143800

In [16]:
# Properly flatten columns
data.columns = data.columns.map(lambda x: x[0] if isinstance(x, tuple) else x)

# Remove column name labels (Price, Ticker)
data.columns.name = None

# Verify
print(data.columns)
data.head()

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

                  Close         High          Low         Open  Volume
Date
2015-01-02  8395.450195  8410.599609  8288.700195  8288.700195  101900
2015-01-05  8378.400391  8445.599609  8363.900391  8407.950195  118200
2015-01-06  8127.350098  8327.849609  8111.350098  8325.299805  172800
2015-01-07  8102.100098  8151.200195  8065.450195  8118.649902  164100
2015-01-08  8234.599609  8243.500000  8167.299805  8191.399902  143800

In [18]:
data.to_csv("../data/nifty50_raw.csv")